version: '3.5'

services:

  viz:
    image: dockersamples/visualizer
    ports:
      - '8888:8080'
    networks:
      - wms
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - db
      - wordpress
      - phpmyadmin

  wordpress:
    container_name: wms_wordpress
    depends_on:
      - db
    image: max2wms/wms
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: password01
    ports:
      - 80:80
    networks:
      - wms

  db:
    container_name: wms_mysql
    image: mysql:5.7
    volumes:
      - ./data/actual/prod:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password01
    networks:
      - wms

  phpmyadmin:
    container_name: wms_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:8080
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password01
    networks:
      - wms

networks:
  wms:
    name: wms